spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: arsen.suranov2003@gmail.com
    password: zkwdlxurvabbtjjs # The generated app password without spaces
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: Thoughts API
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic_db
    username: postgres
    password: 1337
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # can be none, update, create, create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true